name: Scheduled Task Example

on:
  schedule:
    - cron: '0 0 * * *'  # 每天的 9:00 (UTC) 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Current Time
        run: |
          echo "Current Time (UTC): $(date -u)"
          echo "Current Time (Local): $(date)"

      - name: Run a script or command
        run: |
          echo "定时任务测试开始"

  call_meowflow_workflow:
    uses: ./.github/workflows/meowflow.yml  # 调用可复用工作流
    
  call_main_workflow:
    uses: ./.github/workflows/main.yml  # 调用可复用工作流

  complete_task:
    runs-on: ubuntu-latest
    needs: [call_meowflow_workflow, call_main_workflow]  # 依赖前面的任务

    steps:
      - name: Complete scheduled task
        run: |
          echo "定时任务测试结束"
