name: Scheduled Task Example

on:
  schedule:
    - cron: '0 4,10 * * *' # 每天的 02:00 和 10:00 (UTC) 触发

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Current Time
        run: |
          echo "Current Time (UTC): $(date -u)"
          echo "Current Time (Local): $(date)"

      - name: Run a script or command
        run: |
          echo "定时任务测试开始"

      - name: Run meowflow.yml
        run: |
          echo "运行喵福禄API任务开始"

      - name: Run main.yml
        run: |
          echo "运行定制喵API任务开始"
          
      - name: Complete scheduled task
        run: |
          echo "定时任务测试结束"
